name: MC-pocket-discord-bridge
version: '1.0-SNAPSHOT'
main: nl.hampternom.mCPocketDiscordBridge.MCPocketDiscordBridge
api-version: '1.19'

commands:
  discordstats:
    description: Fetch stats for Discord
    usage: /discordstats <username>